before:
  hooks:
  - go mod tidy

builds:
- main: ./cmd/teslamate-discovery
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
universal_binaries:
- replace: true

notarize:
  macos:
    - sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 20m

archives:
- format_overrides:
  - goos: windows
    format: zip
kos:
- base_import_paths: true
  tags:
    - '{{.Version}}'
    - latest
  platforms:
  - linux/amd64
  - linux/arm64
  sbom: none
checksum: {}

changelog:
  use: github-native

snapshot: {}

report_sizes: true
