before:
  hooks:
  - go mod tidy

builds:
- main: ./cmd
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
universal_binaries:
- replace: true

archives:
- format_overrides:
  - goos: windows
    format: zip
kos:
- preserve_import_paths: false
  platforms:
  - linux/amd64
  - linux/arm64
  tags:
    - '{{.Version}}'
    - latest
checksum: {}

changelog:
  use: github-native

snapshot: {}

report_sizes: true
