name: Pull Request Checks
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
jobs:
  check-shell-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@master
    - uses: collin-miller/shfmt-action@v1
      with:
        args: -kp -i 2 -d teslamate-discovery.sh
